# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false

env:
  global:
    - CONDA_PACKAGES="numpy>=1.16 xarray dask-core pytest"

jobs:
  fast_finish: true
  include:
  - python: 3.6
    env: DOCTEST=false
  - python: 3.7
    env: DOCTEST=false
  - python: 3.8
    env: DOCTEST=false
  - python: 3.6
    env: DOCTEST=true

before_install:
  - sudo apt-get install gfortran
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.16.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -n xcape_test_env python="$TRAVIS_PYTHON_VERSION" "$CONDA_PACKAGES"
  - source activate xcape_test_env
  - if [ $DOCTEST == 'false' ];
    then python setup.py build_ext;
    fi
  - pip install .

before_script:
  - pip install codecov pytest-cov

script:
  - if [ $DOCTEST == 'true' ];
    then cd doc; make html;
    else py.test -v --cov=xcape --cov-config .coveragerc --cov-report term-missing;
    fi

after_success:
  - codecov
